"""CapabilityDAG — Self-Growing Universal Knowledge Graph.

A domain-agnostic, community-scalable directed acyclic graph of verified
capabilities. Every piece of knowledge AutoForge accumulates — whether it's
a mathematical proof, a code pattern, an architectural decision, a UI
convention, or a debugging strategy — lives as a node in this graph.

Core principles:
  1. **Content-addressed**: Nodes are identified by content hash,
     enabling deduplication across users/projects/communities.
  2. **Domain-agnostic**: Math proofs, code snippets, design patterns,
     and workflow strategies share the same graph structure.
  3. **Verification-polymorphic**: Each domain defines its own verification
     oracle — Lean type-checker for math, test suites for code, user
     ratings for design, LLM evaluation for everything else.
  4. **Self-growing**: The graph autonomously generates candidate nodes
     (via STP-style mutation/composition) and verifies them.
  5. **Community-mergeable**: Multiple DAG instances can merge, with
     conflict resolution based on verification confidence.
  6. **AI-native retrieval**: No CLI entry points. The AI describes what
     it needs, the DAG returns relevant capabilities.

Architecture:

    CapabilityNode          — Atomic unit: content + metadata + verification
        ↓ depends_on
    CapabilityEdge          — Typed dependency (requires, extends, composes, ...)
        ↓ organized by
    CapabilityDAG           — The graph: add, query, grow, merge, persist
        ↓ verified by
    VerificationOracle      — Pluggable per-domain verification
        ↓ grown by
    AutonomousGrowthEngine  — STP-generalized: mutate → verify → add
        ↓ shared via
    CommunitySync           — Cross-instance merge protocol

The DAG replaces / unifies:
  - FoundationBuilder's block system (lean_prover.py)
  - RAGRetrievalEngine's snippet index (rag_retrieval.py)
  - EvolutionEngine's genome tracking (evolution.py)
  - DynamicConstitution's knowledge base (dynamic_constitution.py)
  - SICA's improvement history (sica.py)
  - ConjectureEngine's proved library (lean_prover.py)

None of those are deleted — they continue to work. The DAG sits underneath
as the universal persistence + retrieval + growth layer. Existing modules
can read from and write to it via simple APIs.

References:
  - STP (ICML 2025): Self-play for autonomous theorem discovery
  - LeanAgent (ICLR 2025): Lifelong learning across repositories
  - FunSearch (Nature 2024): LLM-guided search for novel solutions
  - EUREKA (ICLR 2024): LLM reward design via evolutionary search
  - Voyager (NeurIPS 2023): Open-ended embodied agent skill library
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Protocol

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════
# Enumerations
# ══════════════════════════════════════════════════════════════


class Domain(str, Enum):
    """Knowledge domains — extensible, not exhaustive."""
    MATH_PROOF = "math_proof"           # Lean theorems, proof strategies
    CODE_PATTERN = "code_pattern"       # Reusable code templates, idioms
    ARCHITECTURE = "architecture"       # System design decisions
    UI_DESIGN = "ui_design"             # Visual/UX conventions
    WORKFLOW = "workflow"               # Build/deploy/test strategies
    DEBUGGING = "debugging"             # Bug patterns + fix strategies
    CONSTITUTION = "constitution"       # Agent behavior rules
    DOMAIN_KNOWLEDGE = "domain_knowledge"  # Subject-matter expertise
    GENERAL = "general"                 # Catch-all


class VerificationType(str, Enum):
    """How a capability was verified."""
    FORMAL = "formal"           # Lean type-checker, Z3, etc. — 100% certain
    TEST_SUITE = "test_suite"   # Automated tests passed — high confidence
    LLM_EVAL = "llm_eval"      # LLM evaluated correctness — medium confidence
    COMMUNITY = "community"     # Multiple users confirmed — social proof
    SELF_REPORT = "self_report" # System self-assessed — low confidence
    UNVERIFIED = "unverified"   # Not yet verified


class EdgeType(str, Enum):
    """Relationship between capabilities."""
    DEPENDS_ON = "depends_on"     # B requires A (A → B)
    EXTENDS = "extends"           # B generalizes or strengthens A
    COMPOSES = "composes"         # C = A + B combined
    CONTRADICTS = "contradicts"   # A and B are mutually exclusive
    SUPERSEDES = "supersedes"     # B makes A obsolete
    ANALOGOUS = "analogous"       # A in domain X ≈ B in domain Y
    DERIVED_FROM = "derived_from" # B was generated by mutating A


class GrowthStrategy(str, Enum):
    """How new nodes are generated."""
    GENERALIZE = "generalize"         # Weaken preconditions
    SPECIALIZE = "specialize"         # Strengthen for specific case
    COMPOSE = "compose"               # Combine two existing nodes
    ANALOGIZE = "analogize"           # Transfer across domains
    CONTRAPOSITIVE = "contrapositive" # Logical negation / inversion
    DECOMPOSE = "decompose"           # Break into sub-capabilities
    BOUNDARY_TEST = "boundary_test"   # Test edge cases / limits
    ABSTRACT = "abstract"             # Extract common pattern


# ══════════════════════════════════════════════════════════════
# Core Data Structures
# ══════════════════════════════════════════════════════════════


@dataclass
class CapabilityNode:
    """Atomic unit of knowledge in the DAG.

    Content-addressed: the `id` is derived from (domain, content_hash),
    so identical capabilities across users/projects resolve to the same node.

    Fields:
      - id: Content-based hash (deterministic, dedup-friendly)
      - domain: Which knowledge domain this belongs to
      - content: The actual capability (Lean code, code snippet, design rule, ...)
      - summary: Human/AI-readable one-line description
      - tags: Free-form labels for retrieval
      - verification: How this was verified and confidence level
      - provenance: Where this came from (project, user, generation round)
      - usage_count: How many times this was retrieved and used
      - confidence: 0.0–1.0, grows with verification and usage
      - created_at: Timestamp
      - embedding: Optional semantic vector for retrieval (lazy-computed)
    """
    id: str
    domain: Domain
    content: str
    summary: str = ""
    tags: list[str] = field(default_factory=list)

    # Verification
    verification_type: VerificationType = VerificationType.UNVERIFIED
    confidence: float = 0.1
    verification_details: str = ""

    # Provenance
    source_project: str = ""
    source_user: str = ""
    generation_strategy: str = ""   # Which GrowthStrategy created this
    parent_ids: list[str] = field(default_factory=list)  # Nodes this was derived from

    # Usage tracking
    usage_count: int = 0
    success_count: int = 0          # Times it actually helped
    last_used: float = 0.0

    # Metadata
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    metadata: dict[str, Any] = field(default_factory=dict)

    # Embedding (lazy, not persisted in JSON by default)
    _embedding: list[float] | None = field(default=None, repr=False)

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "domain": self.domain.value,
            "content": self.content,
            "summary": self.summary,
            "tags": self.tags,
            "verification_type": self.verification_type.value,
            "confidence": self.confidence,
            "verification_details": self.verification_details,
            "source_project": self.source_project,
            "source_user": self.source_user,
            "generation_strategy": self.generation_strategy,
            "parent_ids": self.parent_ids,
            "usage_count": self.usage_count,
            "success_count": self.success_count,
            "last_used": self.last_used,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CapabilityNode:
        return cls(
            id=data["id"],
            domain=Domain(data.get("domain", "general")),
            content=data.get("content", ""),
            summary=data.get("summary", ""),
            tags=data.get("tags", []),
            verification_type=VerificationType(data.get("verification_type", "unverified")),
            confidence=data.get("confidence", 0.1),
            verification_details=data.get("verification_details", ""),
            source_project=data.get("source_project", ""),
            source_user=data.get("source_user", ""),
            generation_strategy=data.get("generation_strategy", ""),
            parent_ids=data.get("parent_ids", []),
            usage_count=data.get("usage_count", 0),
            success_count=data.get("success_count", 0),
            last_used=data.get("last_used", 0.0),
            created_at=data.get("created_at", time.time()),
            updated_at=data.get("updated_at", time.time()),
            metadata=data.get("metadata", {}),
        )


@dataclass
class CapabilityEdge:
    """Directed edge between two capability nodes."""
    source_id: str          # From node
    target_id: str          # To node
    edge_type: EdgeType
    weight: float = 1.0     # Strength of relationship
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_id": self.source_id,
            "target_id": self.target_id,
            "edge_type": self.edge_type.value,
            "weight": self.weight,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CapabilityEdge:
        return cls(
            source_id=data["source_id"],
            target_id=data["target_id"],
            edge_type=EdgeType(data.get("edge_type", "depends_on")),
            weight=data.get("weight", 1.0),
            metadata=data.get("metadata", {}),
        )


# ══════════════════════════════════════════════════════════════
# Verification Oracle Protocol
# ══════════════════════════════════════════════════════════════


class VerificationOracle(Protocol):
    """Protocol for domain-specific verification.

    Each domain provides its own oracle:
      - Math: run Lean, get binary pass/fail
      - Code: run test suite, get pass rate
      - Design: LLM evaluation or user feedback
      - Workflow: success rate across projects

    Any object that implements `verify()` qualifies.
    """

    async def verify(
        self,
        node: CapabilityNode,
        context: dict[str, Any],
    ) -> tuple[VerificationType, float, str]:
        """Verify a capability node.

        Returns:
          (verification_type, confidence, details_string)
        """
        ...


class LLMVerificationOracle:
    """Default oracle: uses LLM to evaluate correctness.

    This is the universal fallback. Confidence is capped at 0.7
    because LLM evaluation is not formal verification.
    """

    MAX_CONFIDENCE = 0.7

    async def verify(
        self,
        node: CapabilityNode,
        context: dict[str, Any],
    ) -> tuple[VerificationType, float, str]:
        """Verify using LLM evaluation."""
        llm = context.get("llm")
        if not llm:
            return VerificationType.UNVERIFIED, 0.1, "No LLM available"

        from autoforge.engine.llm_router import TaskComplexity

        prompt = f"""Evaluate the correctness and quality of this {node.domain.value} capability.

## Content
{node.content[:3000]}

## Summary
{node.summary}

## Tags
{', '.join(node.tags)}

Rate on a scale of 0.0 to 1.0:
- correctness: Is this factually/logically correct?
- usefulness: Would this be useful in practice?
- quality: Is it well-written/well-structured?

Return JSON: {{"correctness": 0.0, "usefulness": 0.0, "quality": 0.0, "issues": "..."}}"""

        try:
            response = await llm.call(
                complexity=TaskComplexity.STANDARD,
                system="You evaluate knowledge artifacts for correctness and quality.",
                messages=[{"role": "user", "content": prompt}],
            )
            text = ""
            for block in response.content:
                if block.type == "text":
                    text += block.text

            data = _extract_json(text)
            if data:
                correctness = float(data.get("correctness", 0.5))
                usefulness = float(data.get("usefulness", 0.5))
                quality = float(data.get("quality", 0.5))
                score = (correctness * 0.5 + usefulness * 0.3 + quality * 0.2)
                confidence = min(self.MAX_CONFIDENCE, score)
                issues = data.get("issues", "")
                return VerificationType.LLM_EVAL, confidence, issues
        except Exception as e:
            logger.debug(f"[CapDAG] LLM verification failed: {e}")

        return VerificationType.UNVERIFIED, 0.1, "Verification failed"


class CommunityVerificationOracle:
    """Verification through community usage signals.

    Confidence grows with usage: the more users successfully use a
    capability, the higher its confidence becomes.
    """

    async def verify(
        self,
        node: CapabilityNode,
        context: dict[str, Any],
    ) -> tuple[VerificationType, float, str]:
        """Verify via community signals."""
        if node.usage_count == 0:
            return VerificationType.UNVERIFIED, node.confidence, "No usage data"

        success_rate = node.success_count / max(1, node.usage_count)
        # Bayesian-ish: blend prior (0.5) with observed rate
        # More usage → more weight on observed rate
        alpha = min(1.0, node.usage_count / 20.0)
        blended = (1 - alpha) * 0.5 + alpha * success_rate
        confidence = min(0.9, blended)  # Cap at 0.9 (not formal)

        details = (f"Usage: {node.usage_count}, "
                   f"Success: {node.success_count}, "
                   f"Rate: {success_rate:.2f}")
        return VerificationType.COMMUNITY, confidence, details


# ══════════════════════════════════════════════════════════════
# The DAG
# ══════════════════════════════════════════════════════════════


class CapabilityDAG:
    """Self-growing universal knowledge graph.

    This is the central nervous system of AutoForge's knowledge.
    Every module can read from and write to it.

    Operations:
      - add(node): Insert a new capability
      - query(text, domain, tags, top_k): Retrieve relevant capabilities
      - record_usage(node_id, success): Track usage outcomes
      - grow(domain, llm): Autonomously generate new capabilities
      - merge(other_dag): Merge another DAG (community sync)
      - prune(min_confidence, max_age): Remove low-quality nodes
      - export() / import(): Persistence
    """

    # Confidence thresholds
    PRUNE_THRESHOLD = 0.05       # Below this → candidate for removal
    MATURE_THRESHOLD = 0.6       # Above this → considered reliable
    PROMOTE_USAGE_COUNT = 5      # Uses before eligible for promotion

    def __init__(self, storage_dir: Path | None = None) -> None:
        self._nodes: dict[str, CapabilityNode] = {}
        self._edges: list[CapabilityEdge] = []
        self._adjacency: dict[str, list[str]] = {}     # node_id → [dependent_ids]
        self._reverse_adj: dict[str, list[str]] = {}    # node_id → [dependency_ids]
        self._domain_index: dict[str, set[str]] = {}    # domain → {node_ids}
        self._tag_index: dict[str, set[str]] = {}       # tag → {node_ids}

        self._oracles: dict[Domain, VerificationOracle] = {}
        self._default_oracle = LLMVerificationOracle()
        self._community_oracle = CommunityVerificationOracle()

        self._storage_dir = storage_dir
        self._growth_round = 0

        # Statistics
        self._stats = {
            "nodes_added": 0,
            "nodes_pruned": 0,
            "queries": 0,
            "growth_rounds": 0,
            "merges": 0,
        }

    # ──────── Node Management ────────

    @staticmethod
    def content_id(domain: Domain, content: str) -> str:
        """Generate deterministic content-based ID.

        Same domain + same content → same ID, across all instances.
        This is what enables community deduplication.
        """
        raw = f"{domain.value}:{content.strip()}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]

    def add(
        self,
        content: str,
        domain: Domain,
        *,
        summary: str = "",
        tags: list[str] | None = None,
        confidence: float = 0.1,
        verification_type: VerificationType = VerificationType.UNVERIFIED,
        source_project: str = "",
        source_user: str = "",
        parent_ids: list[str] | None = None,
        generation_strategy: str = "",
        metadata: dict[str, Any] | None = None,
    ) -> CapabilityNode:
        """Add a capability to the DAG.

        If an identical node exists (same content hash), merges by
        updating confidence and usage stats rather than duplicating.
        """
        node_id = self.content_id(domain, content)

        if node_id in self._nodes:
            existing = self._nodes[node_id]
            # Merge: boost confidence, update metadata
            existing.confidence = min(1.0, max(existing.confidence, confidence))
            existing.usage_count += 1
            existing.updated_at = time.time()
            if tags:
                for t in tags:
                    if t not in existing.tags:
                        existing.tags.append(t)
                        self._index_tag(t, node_id)
            logger.debug(f"[CapDAG] Merged into existing node {node_id[:8]}")
            return existing

        node = CapabilityNode(
            id=node_id,
            domain=domain,
            content=content,
            summary=summary or content[:100],
            tags=tags or [],
            confidence=confidence,
            verification_type=verification_type,
            source_project=source_project,
            source_user=source_user,
            parent_ids=parent_ids or [],
            generation_strategy=generation_strategy,
            metadata=metadata or {},
        )

        self._nodes[node_id] = node
        self._index_node(node)

        # Add edges from parent nodes
        for pid in node.parent_ids:
            if pid in self._nodes:
                self.add_edge(pid, node_id, EdgeType.DERIVED_FROM)

        self._stats["nodes_added"] += 1
        logger.debug(f"[CapDAG] Added {domain.value} node {node_id[:8]}: {summary[:50]}")
        return node

    def add_edge(
        self,
        source_id: str,
        target_id: str,
        edge_type: EdgeType,
        weight: float = 1.0,
    ) -> CapabilityEdge | None:
        """Add a directed edge. Returns None if it would create a cycle."""
        if source_id not in self._nodes or target_id not in self._nodes:
            return None

        # Cycle check (simple DFS)
        if self._would_create_cycle(source_id, target_id):
            logger.debug(f"[CapDAG] Rejected edge {source_id[:8]}→{target_id[:8]} (cycle)")
            return None

        # Deduplicate edges
        for edge in self._edges:
            if (edge.source_id == source_id and edge.target_id == target_id
                    and edge.edge_type == edge_type):
                edge.weight = max(edge.weight, weight)
                return edge

        edge = CapabilityEdge(
            source_id=source_id,
            target_id=target_id,
            edge_type=edge_type,
            weight=weight,
        )
        self._edges.append(edge)

        if source_id not in self._adjacency:
            self._adjacency[source_id] = []
        self._adjacency[source_id].append(target_id)

        if target_id not in self._reverse_adj:
            self._reverse_adj[target_id] = []
        self._reverse_adj[target_id].append(source_id)

        return edge

    def get(self, node_id: str) -> CapabilityNode | None:
        """Get a node by ID."""
        return self._nodes.get(node_id)

    def remove(self, node_id: str) -> bool:
        """Remove a node and its edges."""
        if node_id not in self._nodes:
            return False

        node = self._nodes.pop(node_id)

        # Remove from indices
        domain_key = node.domain.value
        if domain_key in self._domain_index:
            self._domain_index[domain_key].discard(node_id)
        for tag in node.tags:
            if tag in self._tag_index:
                self._tag_index[tag].discard(node_id)

        # Remove edges
        self._edges = [
            e for e in self._edges
            if e.source_id != node_id and e.target_id != node_id
        ]
        self._adjacency.pop(node_id, None)
        self._reverse_adj.pop(node_id, None)
        for adj_list in self._adjacency.values():
            while node_id in adj_list:
                adj_list.remove(node_id)
        for adj_list in self._reverse_adj.values():
            while node_id in adj_list:
                adj_list.remove(node_id)

        self._stats["nodes_pruned"] += 1
        return True

    # ──────── Retrieval ────────

    def query(
        self,
        text: str = "",
        *,
        domain: Domain | None = None,
        tags: list[str] | None = None,
        min_confidence: float = 0.0,
        top_k: int = 10,
    ) -> list[CapabilityNode]:
        """Retrieve relevant capabilities.

        Scoring combines:
          1. Text relevance (word overlap, simple BM25-style)
          2. Domain match (exact domain → bonus)
          3. Tag match (overlapping tags → bonus)
          4. Confidence (higher → better)
          5. Freshness (recently used → slight bonus)
        """
        self._stats["queries"] += 1

        candidates = set(self._nodes.keys())

        # Domain filter
        if domain:
            domain_nodes = self._domain_index.get(domain.value, set())
            candidates &= domain_nodes

        # Tag filter (OR semantics: any matching tag)
        if tags:
            tag_nodes: set[str] = set()
            for tag in tags:
                tag_nodes |= self._tag_index.get(tag.lower(), set())
            if tag_nodes:
                candidates &= tag_nodes

        # Score candidates
        query_words = set(re.findall(r'\w+', text.lower())) if text else set()
        scored: list[tuple[float, CapabilityNode]] = []

        for nid in candidates:
            node = self._nodes[nid]
            if node.confidence < min_confidence:
                continue

            score = 0.0

            # Text relevance
            if query_words:
                node_text = f"{node.summary} {node.content[:500]} {' '.join(node.tags)}".lower()
                node_words = set(re.findall(r'\w+', node_text))
                overlap = len(query_words & node_words)
                if overlap > 0:
                    score += min(1.0, overlap / max(1, len(query_words))) * 0.4
                else:
                    continue  # No text match → skip

            # Confidence
            score += node.confidence * 0.3

            # Usage signal
            if node.usage_count > 0:
                success_rate = node.success_count / max(1, node.usage_count)
                score += success_rate * 0.2

            # Freshness (decay over 30 days)
            age_days = (time.time() - node.updated_at) / 86400
            freshness = max(0, 1.0 - age_days / 30)
            score += freshness * 0.1

            scored.append((score, node))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [node for _, node in scored[:top_k]]

    def query_dependencies(self, node_id: str) -> list[CapabilityNode]:
        """Get all nodes that this node depends on (transitive)."""
        visited: set[str] = set()
        result: list[CapabilityNode] = []

        def dfs(nid: str) -> None:
            if nid in visited:
                return
            visited.add(nid)
            for dep_id in self._reverse_adj.get(nid, []):
                if dep_id in self._nodes:
                    result.append(self._nodes[dep_id])
                    dfs(dep_id)

        dfs(node_id)
        return result

    def query_dependents(self, node_id: str) -> list[CapabilityNode]:
        """Get all nodes that depend on this node (transitive)."""
        visited: set[str] = set()
        result: list[CapabilityNode] = []

        def dfs(nid: str) -> None:
            if nid in visited:
                return
            visited.add(nid)
            for dep_id in self._adjacency.get(nid, []):
                if dep_id in self._nodes:
                    result.append(self._nodes[dep_id])
                    dfs(dep_id)

        dfs(node_id)
        return result

    # ──────── Usage Tracking ────────

    def record_usage(self, node_id: str, success: bool) -> None:
        """Record that a node was used (and whether it helped).

        This is the primary feedback signal. Every time the AI retrieves
        and uses a capability, it calls this with the outcome.
        """
        node = self._nodes.get(node_id)
        if not node:
            return

        node.usage_count += 1
        if success:
            node.success_count += 1
        node.last_used = time.time()
        node.updated_at = time.time()

        # Confidence update: Bayesian-style with usage evidence
        if node.usage_count >= self.PROMOTE_USAGE_COUNT:
            success_rate = node.success_count / node.usage_count
            # Blend: 60% current confidence, 40% observed success rate
            node.confidence = min(
                0.95,
                node.confidence * 0.6 + success_rate * 0.4,
            )

    # ──────── Verification ────────

    def register_oracle(self, domain: Domain, oracle: VerificationOracle) -> None:
        """Register a domain-specific verification oracle."""
        self._oracles[domain] = oracle

    async def verify_node(
        self,
        node_id: str,
        context: dict[str, Any],
    ) -> tuple[VerificationType, float]:
        """Verify a node using the appropriate oracle.

        Falls back to LLM oracle if no domain-specific oracle is registered.
        """
        node = self._nodes.get(node_id)
        if not node:
            return VerificationType.UNVERIFIED, 0.0

        oracle = self._oracles.get(node.domain, self._default_oracle)
        vtype, confidence, details = await oracle.verify(node, context)

        node.verification_type = vtype
        node.confidence = max(node.confidence, confidence)
        node.verification_details = details
        node.updated_at = time.time()

        return vtype, confidence

    # ──────── Autonomous Growth ────────

    async def grow(
        self,
        domain: Domain,
        llm: Any,
        *,
        num_candidates: int = 5,
        base_nodes: list[str] | None = None,
        strategy: GrowthStrategy | None = None,
    ) -> list[CapabilityNode]:
        """Autonomously generate new capability nodes.

        Generalized STP: works for any domain, not just math proofs.

        Pipeline:
          1. Select seed nodes (highest-confidence in the domain)
          2. Apply growth strategy (generalize, compose, analogize, ...)
          3. Generate candidates via LLM
          4. Verify candidates
          5. Add verified ones to the DAG
        """
        from autoforge.engine.llm_router import TaskComplexity
        self._growth_round += 1

        # Select seeds
        if base_nodes:
            seeds = [self._nodes[nid] for nid in base_nodes if nid in self._nodes]
        else:
            domain_nodes = [
                self._nodes[nid]
                for nid in self._domain_index.get(domain.value, set())
            ]
            domain_nodes.sort(key=lambda n: n.confidence, reverse=True)
            seeds = domain_nodes[:10]

        if not seeds:
            logger.info(f"[CapDAG] No seeds for {domain.value}, cannot grow")
            return []

        # Select strategy
        selected_strategy = strategy or self._select_growth_strategy(seeds)

        seed_text = "\n".join(
            f"- [{s.domain.value}] {s.summary} (confidence: {s.confidence:.2f})"
            for s in seeds[:8]
        )
        seed_content = "\n---\n".join(
            s.content[:500] for s in seeds[:5]
        )

        prompt = f"""You are a knowledge growth engine. Generate {num_candidates} new
{domain.value} capabilities by applying the "{selected_strategy.value}" strategy
to these existing capabilities:

## Existing Capabilities (seeds)
{seed_text}

## Seed Content Samples
{seed_content}

## Growth Strategy: {selected_strategy.value}
{self._strategy_description(selected_strategy)}

## Instructions
Generate {num_candidates} new capabilities that:
- Are distinct from the seeds (not duplicates)
- Are plausibly correct and useful
- Follow naturally from the seeds via the specified strategy
- Range in difficulty from accessible to challenging

Return JSON array:
[
  {{
    "content": "the actual capability content (code/proof/rule/pattern)",
    "summary": "one-line description",
    "tags": ["tag1", "tag2"],
    "parent_summaries": ["which seed(s) this derives from"]
  }}
]"""

        try:
            response = await llm.call(
                complexity=TaskComplexity.COMPLEX,
                system="You generate novel knowledge artifacts for a self-growing capability graph.",
                messages=[{"role": "user", "content": prompt}],
            )
            text = ""
            for block in response.content:
                if block.type == "text":
                    text += block.text

            new_nodes: list[CapabilityNode] = []

            if "[" in text:
                json_str = text[text.index("["):text.rindex("]") + 1]
                items = json.loads(json_str)

                for item in items:
                    if not isinstance(item, dict) or "content" not in item:
                        continue

                    # Find parent IDs by matching summaries
                    parent_ids = []
                    for ps in item.get("parent_summaries", []):
                        for seed in seeds:
                            if ps.lower() in seed.summary.lower() or seed.summary.lower() in ps.lower():
                                parent_ids.append(seed.id)
                                break

                    node = self.add(
                        content=item["content"],
                        domain=domain,
                        summary=item.get("summary", ""),
                        tags=item.get("tags", []),
                        confidence=0.15,  # Low initial confidence
                        verification_type=VerificationType.SELF_REPORT,
                        parent_ids=parent_ids,
                        generation_strategy=selected_strategy.value,
                    )
                    new_nodes.append(node)

            # Verify new nodes
            context = {"llm": llm}
            for node in new_nodes:
                await self.verify_node(node.id, context)

            self._stats["growth_rounds"] += 1
            logger.info(
                f"[CapDAG] Growth round {self._growth_round}: "
                f"generated {len(new_nodes)} {domain.value} nodes "
                f"via {selected_strategy.value}"
            )
            return new_nodes

        except Exception as e:
            logger.warning(f"[CapDAG] Growth failed: {e}")
            return []

    def _select_growth_strategy(self, seeds: list[CapabilityNode]) -> GrowthStrategy:
        """Select best growth strategy based on current DAG state."""
        # Heuristic: rotate strategies, prefer composition when graph is large
        strategies = list(GrowthStrategy)
        if len(self._nodes) > 20:
            # Enough nodes to compose
            return GrowthStrategy.COMPOSE
        if len(self._nodes) > 10:
            return strategies[self._growth_round % len(strategies)]
        # Early: prefer generalize and specialize
        return [GrowthStrategy.GENERALIZE, GrowthStrategy.SPECIALIZE][
            self._growth_round % 2
        ]

    @staticmethod
    def _strategy_description(strategy: GrowthStrategy) -> str:
        """Human-readable description of a growth strategy."""
        return {
            GrowthStrategy.GENERALIZE: "Weaken preconditions or broaden applicability. "
                "If a pattern works for X, can it work for a more general class?",
            GrowthStrategy.SPECIALIZE: "Strengthen for a specific case. "
                "Provide more efficient/precise variants for common subcases.",
            GrowthStrategy.COMPOSE: "Combine two or more existing capabilities into a new one. "
                "Look for capabilities that complement each other.",
            GrowthStrategy.ANALOGIZE: "Transfer a pattern from one domain to another. "
                "A code pattern might inspire a design rule, or vice versa.",
            GrowthStrategy.CONTRAPOSITIVE: "State the negation, converse, or dual. "
                "What does the opposite look like? What are the failure modes?",
            GrowthStrategy.DECOMPOSE: "Break a complex capability into simpler sub-capabilities. "
                "Identify the atomic building blocks.",
            GrowthStrategy.BOUNDARY_TEST: "Test edge cases and limits. "
                "What happens at the boundaries? When does this break?",
            GrowthStrategy.ABSTRACT: "Extract the common pattern from multiple concrete instances. "
                "What's the shared structure underneath?",
        }.get(strategy, "Generate novel capabilities.")

    # ──────── Community Merge ────────

    def merge(self, other: CapabilityDAG) -> dict[str, int]:
        """Merge another DAG into this one.

        Merge policy:
          - Same content hash → keep higher confidence, sum usage counts
          - New nodes → add with original confidence
          - Conflicting edges → keep both (graph is DAG, edges don't conflict)

        Returns merge statistics.
        """
        stats = {"new_nodes": 0, "merged_nodes": 0, "new_edges": 0}

        for nid, node in other._nodes.items():
            if nid in self._nodes:
                # Merge existing
                existing = self._nodes[nid]
                existing.confidence = max(existing.confidence, node.confidence)
                existing.usage_count += node.usage_count
                existing.success_count += node.success_count
                existing.updated_at = max(existing.updated_at, node.updated_at)
                for tag in node.tags:
                    if tag not in existing.tags:
                        existing.tags.append(tag)
                        self._index_tag(tag, nid)
                stats["merged_nodes"] += 1
            else:
                # Add new
                self._nodes[nid] = node
                self._index_node(node)
                stats["new_nodes"] += 1

        for edge in other._edges:
            existing = any(
                e.source_id == edge.source_id
                and e.target_id == edge.target_id
                and e.edge_type == edge.edge_type
                for e in self._edges
            )
            if not existing:
                self.add_edge(edge.source_id, edge.target_id, edge.edge_type, edge.weight)
                stats["new_edges"] += 1

        self._stats["merges"] += 1
        logger.info(f"[CapDAG] Merged: +{stats['new_nodes']} new, "
                     f"{stats['merged_nodes']} merged, +{stats['new_edges']} edges")
        return stats

    # ──────── Pruning ────────

    def prune(
        self,
        min_confidence: float = 0.05,
        max_age_days: float = 90,
        protect_verified: bool = True,
    ) -> int:
        """Remove low-quality or stale nodes.

        Protection rules:
          - Formally verified nodes are never pruned
          - Nodes with high usage are never pruned
          - Nodes with dependents are never pruned (would break the DAG)
        """
        now = time.time()
        to_remove: list[str] = []

        for nid, node in self._nodes.items():
            # Protection
            if protect_verified and node.verification_type == VerificationType.FORMAL:
                continue
            if node.usage_count >= self.PROMOTE_USAGE_COUNT:
                continue
            if nid in self._adjacency and self._adjacency[nid]:
                continue  # Has dependents

            # Prune criteria
            age_days = (now - node.created_at) / 86400
            if node.confidence < min_confidence and age_days > 7:
                to_remove.append(nid)
            elif age_days > max_age_days and node.usage_count == 0:
                to_remove.append(nid)

        for nid in to_remove:
            self.remove(nid)

        if to_remove:
            logger.info(f"[CapDAG] Pruned {len(to_remove)} nodes")
        return len(to_remove)

    # ──────── Indexing ────────

    def _index_node(self, node: CapabilityNode) -> None:
        """Add node to all indices."""
        domain_key = node.domain.value
        if domain_key not in self._domain_index:
            self._domain_index[domain_key] = set()
        self._domain_index[domain_key].add(node.id)

        for tag in node.tags:
            self._index_tag(tag, node.id)

    def _index_tag(self, tag: str, node_id: str) -> None:
        """Add a tag → node_id mapping."""
        tag_lower = tag.lower()
        if tag_lower not in self._tag_index:
            self._tag_index[tag_lower] = set()
        self._tag_index[tag_lower].add(node_id)

    def _would_create_cycle(self, source_id: str, target_id: str) -> bool:
        """Check if adding source→target would create a cycle."""
        if source_id == target_id:
            return True

        # BFS from target to see if we can reach source
        visited: set[str] = set()
        queue = deque([target_id])

        while queue:
            current = queue.popleft()
            if current == source_id:
                return True
            if current in visited:
                continue
            visited.add(current)
            queue.extend(self._adjacency.get(current, []))

        return False

    # ──────── Persistence ────────

    def save(self, path: Path | None = None) -> None:
        """Persist DAG to disk."""
        save_path = path or self._storage_dir
        if not save_path:
            logger.warning("[CapDAG] No storage path configured")
            return

        save_path.mkdir(parents=True, exist_ok=True)

        data = {
            "version": 1,
            "growth_round": self._growth_round,
            "stats": self._stats,
            "nodes": {nid: node.to_dict() for nid, node in self._nodes.items()},
            "edges": [e.to_dict() for e in self._edges],
        }

        (save_path / "capability_dag.json").write_text(
            json.dumps(data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info(f"[CapDAG] Saved: {len(self._nodes)} nodes, {len(self._edges)} edges")

    def to_dict(self) -> dict[str, Any]:
        """Serialize DAG into a JSON-safe dict for federation sync."""
        return {
            "version": 1,
            "growth_round": self._growth_round,
            "stats": self._stats,
            "nodes": {nid: node.to_dict() for nid, node in self._nodes.items()},
            "edges": [e.to_dict() for e in self._edges],
        }

    def load_dict(self, data: dict[str, Any]) -> bool:
        """Load DAG state from in-memory dict.

        Existing graph content is preserved; input data is merged into current state.
        """
        try:
            incoming = CapabilityDAG()
            incoming._growth_round = int(data.get("growth_round", 0))
            incoming._stats = data.get("stats", incoming._stats)

            for ndata in data.get("nodes", {}).values():
                node = CapabilityNode.from_dict(ndata)
                incoming._nodes[node.id] = node
                incoming._index_node(node)

            for edata in data.get("edges", []):
                edge = CapabilityEdge.from_dict(edata)
                incoming._edges.append(edge)
                incoming._adjacency.setdefault(edge.source_id, []).append(edge.target_id)
                incoming._reverse_adj.setdefault(edge.target_id, []).append(edge.source_id)

            self._growth_round = max(self._growth_round, incoming._growth_round)
            self.merge(incoming)
            return True
        except Exception as e:
            logger.warning(f"[CapDAG] load_dict failed: {e}")
            return False

    def load(self, path: Path | None = None) -> bool:
        """Load DAG from disk."""
        load_path = path or self._storage_dir
        if not load_path:
            return False

        dag_file = load_path / "capability_dag.json"
        if not dag_file.exists():
            return False

        try:
            data = json.loads(dag_file.read_text(encoding="utf-8"))
            if not self.load_dict(data):
                return False

            logger.info(f"[CapDAG] Loaded: {len(self._nodes)} nodes, "
                        f"{len(self._edges)} edges")
            return True

        except Exception as e:
            logger.warning(f"[CapDAG] Load failed: {e}")
            return False

    # ──────── Statistics & Introspection ────────

    def get_stats(self) -> dict[str, Any]:
        """Comprehensive DAG statistics."""
        domain_counts = {
            d: len(nids) for d, nids in self._domain_index.items()
        }
        confidence_dist = {
            "unverified": 0, "low": 0, "medium": 0, "high": 0, "formal": 0,
        }
        for node in self._nodes.values():
            if node.verification_type == VerificationType.FORMAL:
                confidence_dist["formal"] += 1
            elif node.confidence < 0.3:
                confidence_dist["low"] += 1
            elif node.confidence < 0.6:
                confidence_dist["medium"] += 1
            elif node.confidence < 0.9:
                confidence_dist["high"] += 1
            else:
                confidence_dist["high"] += 1

        return {
            "total_nodes": len(self._nodes),
            "total_edges": len(self._edges),
            "domains": domain_counts,
            "confidence_distribution": confidence_dist,
            "growth_rounds": self._growth_round,
            "operations": dict(self._stats),
        }

    def get_frontier(self, domain: Domain | None = None, top_k: int = 10) -> list[CapabilityNode]:
        """Get the 'frontier' — highest-confidence leaf nodes.

        These are the most mature capabilities that other capabilities
        can be built upon. The growing edge of the knowledge graph.
        """
        candidates = []
        for nid, node in self._nodes.items():
            if domain and node.domain != domain:
                continue
            # Leaf = no outgoing DERIVED_FROM edges (nothing derived from it yet)
            has_children = any(
                e.source_id == nid and e.edge_type == EdgeType.DERIVED_FROM
                for e in self._edges
            )
            if not has_children:
                candidates.append(node)

        candidates.sort(key=lambda n: n.confidence, reverse=True)
        return candidates[:top_k]

    @property
    def size(self) -> int:
        return len(self._nodes)

    def __len__(self) -> int:
        return len(self._nodes)

    def __contains__(self, node_id: str) -> bool:
        return node_id in self._nodes


# ══════════════════════════════════════════════════════════════
# Bridge Adapters (connect existing modules to the DAG)
# ══════════════════════════════════════════════════════════════


class DAGBridge:
    """Bridges existing AutoForge modules to the CapabilityDAG.

    Provides convenience methods so that existing modules (RAG, Evolution,
    SICA, LeanProver, etc.) can read/write to the DAG without knowing
    its internal structure.

    Usage by existing modules:
      - RAG: bridge.ingest_code_snippet(...)
      - Evolution: bridge.ingest_workflow_genome(...)
      - SICA: bridge.ingest_constitution_patch(...)
      - LeanProver: bridge.ingest_proof(...)
      - Any new domain: bridge.ingest(domain, content, ...)
    """

    def __init__(self, dag: CapabilityDAG) -> None:
        self._dag = dag

    # ── Generic ──

    def ingest(
        self,
        domain: Domain,
        content: str,
        summary: str = "",
        tags: list[str] | None = None,
        confidence: float = 0.2,
        **kwargs: Any,
    ) -> CapabilityNode:
        """Universal ingestion point."""
        return self._dag.add(
            content=content,
            domain=domain,
            summary=summary,
            tags=tags,
            confidence=confidence,
            **kwargs,
        )

    # ── Code Patterns (from RAG) ──

    def ingest_code_snippet(
        self,
        code: str,
        language: str,
        function_name: str = "",
        docstring: str = "",
        source_project: str = "",
        quality_score: float = 0.5,
    ) -> CapabilityNode:
        """Ingest a code snippet from RAG retrieval."""
        tags = [language]
        if function_name:
            tags.append(function_name)

        return self._dag.add(
            content=code,
            domain=Domain.CODE_PATTERN,
            summary=docstring or f"{language} function: {function_name}",
            tags=tags,
            confidence=quality_score * 0.8,
            verification_type=VerificationType.SELF_REPORT,
            source_project=source_project,
        )

    # ── Math Proofs (from LeanProver) ──

    def ingest_proof(
        self,
        lean_code: str,
        theorem_name: str = "",
        informal_statement: str = "",
        verified: bool = False,
        source_project: str = "",
    ) -> CapabilityNode:
        """Ingest a Lean 4 proof."""
        return self._dag.add(
            content=lean_code,
            domain=Domain.MATH_PROOF,
            summary=informal_statement or f"theorem {theorem_name}",
            tags=["lean4", "proof"] + ([theorem_name] if theorem_name else []),
            confidence=0.95 if verified else 0.3,
            verification_type=VerificationType.FORMAL if verified else VerificationType.LLM_EVAL,
            source_project=source_project,
        )

    # ── Workflow Patterns (from Evolution) ──

    def ingest_workflow(
        self,
        strategy_description: str,
        tech_fingerprint: str = "",
        fitness: float = 0.5,
        source_project: str = "",
    ) -> CapabilityNode:
        """Ingest a workflow genome / strategy."""
        tags = ["workflow"]
        if tech_fingerprint:
            tags.extend(tech_fingerprint.split("-"))

        return self._dag.add(
            content=strategy_description,
            domain=Domain.WORKFLOW,
            summary=f"Workflow: {strategy_description[:80]}",
            tags=tags,
            confidence=fitness,
            verification_type=VerificationType.TEST_SUITE,
            source_project=source_project,
        )

    # ── Constitution Rules (from SICA / DynamicConstitution) ──

    def ingest_constitution_patch(
        self,
        patch_content: str,
        target_role: str = "",
        source: str = "",
        priority: int = 5,
    ) -> CapabilityNode:
        """Ingest a constitution patch."""
        return self._dag.add(
            content=patch_content,
            domain=Domain.CONSTITUTION,
            summary=f"Constitution rule for {target_role}: {patch_content[:60]}",
            tags=["constitution", target_role, source],
            confidence=0.5,
            verification_type=VerificationType.SELF_REPORT,
            metadata={"priority": priority},
        )

    # ── Architecture Decisions ──

    def ingest_architecture_decision(
        self,
        decision: str,
        context: str = "",
        outcome_success: bool = True,
        source_project: str = "",
    ) -> CapabilityNode:
        """Ingest an architectural decision and its outcome."""
        return self._dag.add(
            content=f"{decision}\n\n## Context\n{context}" if context else decision,
            domain=Domain.ARCHITECTURE,
            summary=decision[:100],
            tags=["architecture"],
            confidence=0.7 if outcome_success else 0.2,
            verification_type=VerificationType.TEST_SUITE if outcome_success
                             else VerificationType.SELF_REPORT,
            source_project=source_project,
        )

    # ── Debugging Knowledge ──

    def ingest_debug_pattern(
        self,
        error_pattern: str,
        fix_strategy: str,
        success: bool = True,
        source_project: str = "",
    ) -> CapabilityNode:
        """Ingest a debugging pattern (error → fix mapping)."""
        content = f"## Error Pattern\n{error_pattern}\n\n## Fix\n{fix_strategy}"
        return self._dag.add(
            content=content,
            domain=Domain.DEBUGGING,
            summary=f"Fix for: {error_pattern[:60]}",
            tags=["debugging", "error-fix"],
            confidence=0.7 if success else 0.2,
            verification_type=VerificationType.TEST_SUITE if success
                             else VerificationType.SELF_REPORT,
            source_project=source_project,
        )

    # ── Query helpers ──

    def find_relevant(
        self,
        description: str,
        domain: Domain | None = None,
        top_k: int = 5,
    ) -> list[CapabilityNode]:
        """Find relevant capabilities for a given description.

        This is the main AI-facing API: describe what you need,
        get back relevant capabilities.
        """
        return self._dag.query(
            description,
            domain=domain,
            min_confidence=0.1,
            top_k=top_k,
        )

    def build_context(
        self,
        description: str,
        domain: Domain | None = None,
        max_tokens: int = 4000,
    ) -> str:
        """Build a context string from relevant capabilities.

        This is what gets injected into agent prompts — the AI doesn't
        need to know about the DAG structure, it just sees relevant
        knowledge formatted as context.
        """
        nodes = self.find_relevant(description, domain=domain, top_k=10)
        if not nodes:
            return ""

        parts = [f"## Relevant Capabilities ({len(nodes)} found)\n"]
        total_chars = 0

        for node in nodes:
            entry = (
                f"### [{node.domain.value}] {node.summary}\n"
                f"Confidence: {node.confidence:.2f} | "
                f"Used: {node.usage_count}× | "
                f"Tags: {', '.join(node.tags[:5])}\n"
                f"```\n{node.content[:1000]}\n```\n"
            )
            if total_chars + len(entry) > max_tokens * 4:  # ~4 chars per token
                break
            parts.append(entry)
            total_chars += len(entry)

        return "\n".join(parts)


# ══════════════════════════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════════════════════════


def _extract_json(text: str) -> dict[str, Any] | None:
    """Robustly extract JSON object from LLM output."""
    if "{" not in text:
        return None
    try:
        json_str = text[text.index("{"):text.rindex("}") + 1]
        return json.loads(json_str)
    except (json.JSONDecodeError, ValueError):
        match = re.search(r"\{[^{}]*\}", text)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass
    return None
