"""Lean 4 Formal Theorem Proving — Core data structures, environment, and main engine.

Contains:
  - ProofStatus, TacticSource, DifficultyTier enums
  - ProofState, TacticCandidate, ProofStep, ProofAttempt, ProofSearchNode,
    Conjecture, FoundationBlock, LeanVerificationResult dataclasses
  - LeanEnvironment: Lean 4 toolchain interaction (verify, init project)
  - PantographREPL: Interactive REPL-style proof execution
  - LeanProver: Main orchestrating engine
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from autoforge.engine.runtime.commands import run_args, spawn_exec

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════
# Data Structures
# ══════════════════════════════════════════════════════════════


class ProofStatus(str, Enum):
    """Status of a proof attempt."""
    UNPROVEN = "unproven"
    PROVING = "proving"
    PROVED = "proved"
    FORMALIZED = "formalized"
    COMPILES = "compiles"
    VERIFIED_WITH_SORRY = "verified_with_sorry"
    FAILED = "failed"
    DECOMPOSED = "decomposed"  # Broken into subgoals
    SORRY = "sorry"            # Has 'sorry' placeholder


class TacticSource(str, Enum):
    """Where a tactic suggestion came from."""
    LLM_INFORMAL = "llm_informal"     # Informal reasoning → tactic
    LLM_DIRECT = "llm_direct"         # Direct tactic generation
    RETRIEVAL = "retrieval"            # Retrieved from proof library
    AESOP = "aesop"                    # Lean's aesop tactic
    SIMP = "simp"                      # Lean's simp tactic
    OMEGA = "omega"                    # Lean's omega tactic
    DECOMPOSITION = "decomposition"    # Subgoal decomposition
    SELF_PLAY = "self_play"            # Self-play conjecture proof


class DifficultyTier(str, Enum):
    """Mathematical difficulty tier (curriculum learning)."""
    FOUNDATION = "foundation"   # Axioms, basic logic
    ELEMENTARY = "elementary"   # High-school level
    COMPETITION = "competition" # AMC/AIME level
    OLYMPIAD = "olympiad"       # IMO level
    RESEARCH = "research"       # Open problems / novel results


@dataclass
class ProofState:
    """Current state within a proof attempt (Pantograph-style)."""
    goals: list[str]                 # Remaining proof goals
    hypotheses: list[str]            # Available hypotheses
    context: str = ""                # Full tactic state as string
    depth: int = 0                   # Depth in proof tree
    parent_tactic: str = ""          # Tactic that led to this state


@dataclass
class TacticCandidate:
    """A candidate tactic to apply at a proof state."""
    tactic: str                         # The Lean 4 tactic text
    source: TacticSource                # Where it came from
    confidence: float = 0.5             # Estimated probability of success
    informal_reasoning: str = ""        # Chain-of-thought behind it
    retrieval_context: list[str] = field(default_factory=list)  # Relevant lemmas


@dataclass
class ProofStep:
    """One step in a proof attempt."""
    state_before: ProofState
    tactic_applied: str
    state_after: ProofState | None = None  # None if tactic failed
    success: bool = False
    error_message: str = ""
    source: TacticSource = TacticSource.LLM_DIRECT
    thinking: str = ""                     # Informal reasoning trace


@dataclass
class ProofAttempt:
    """A complete proof attempt for a theorem."""
    theorem_id: str
    statement: str                  # Lean 4 theorem statement
    informal_statement: str = ""    # Natural language version
    informal_proof: str = ""        # Natural language proof sketch
    status: ProofStatus = ProofStatus.UNPROVEN
    steps: list[ProofStep] = field(default_factory=list)
    lean_proof: str = ""            # Final Lean 4 proof text
    subgoals: list[str] = field(default_factory=list)
    difficulty: DifficultyTier = DifficultyTier.ELEMENTARY
    attempts: int = 0
    verification_time: float = 0.0
    error: str = ""


@dataclass
class ProofSearchNode:
    """Node in MCTS proof search tree (DeepSeek-Prover-V1.5 style)."""
    state: ProofState
    tactic: str = ""                 # Tactic applied to reach this node
    parent: ProofSearchNode | None = None
    children: list[ProofSearchNode] = field(default_factory=list)
    visits: int = 0
    value: float = 0.0               # Estimated proof completion probability
    depth: int = 0
    is_terminal: bool = False         # Proof complete or dead end


@dataclass
class Conjecture:
    """A conjecture generated by the self-play engine (STP style)."""
    id: str
    lean_statement: str
    informal_statement: str = ""
    source_theorem: str = ""         # Theorem it was derived from
    difficulty_estimate: float = 0.5
    proved: bool = False
    proof: str = ""
    generation_round: int = 0


@dataclass
class FoundationBlock:
    """A verified building block in our foundation (zero-axiom approach)."""
    id: str
    name: str
    lean_code: str
    dependencies: list[str] = field(default_factory=list)
    category: str = ""               # "logic", "set", "number", "algebra", etc.
    tier: DifficultyTier = DifficultyTier.FOUNDATION
    verified: bool = False
    proof_hash: str = ""             # Content hash for dedup


@dataclass
class LeanVerificationResult:
    """Result of running Lean 4 on a file."""
    success: bool
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    sorry_count: int = 0             # Number of sorry placeholders
    execution_time: float = 0.0


# ══════════════════════════════════════════════════════════════
# Lean Environment (Pantograph-inspired REPL)
# ══════════════════════════════════════════════════════════════


class LeanEnvironment:
    """Manages interaction with Lean 4 toolchain.

    Provides Pantograph-style machine-to-machine interaction:
      - File-based verification (lake build)
      - REPL-style tactic application
      - Proof state inspection
      - Expression type checking

    Falls back to LLM-simulated verification when Lean is not installed,
    with clear warnings about reduced trustworthiness.
    """

    def __init__(self, workspace: Path | None = None) -> None:
        self._workspace = workspace or Path(".")
        self._lean_available: bool | None = None
        self._lean_version: str = ""
        self._mathlib_available = False
        self._lake_env: dict[str, str] = {}

    async def check_lean_installation(self) -> bool:
        """Detect whether Lean 4 and lake are available."""
        if self._lean_available is not None:
            return self._lean_available

        import shutil
        lean_path = shutil.which("lean")
        lake_path = shutil.which("lake")

        if lean_path and lake_path:
            try:
                res = await run_args(
                    ["lean", "--version"],
                    cwd=self._workspace,
                    timeout_s=10.0,
                    max_stdout_chars=2000,
                    max_stderr_chars=2000,
                    label="lean.version",
                )
                version_text = (res.stdout or "").strip()
                if res.exit_code == 0 and "Lean" in version_text:
                    self._lean_available = True
                    self._lean_version = version_text
                    logger.info(f"[Lean] Found: {version_text}")
                    return True
            except Exception as e:
                logger.debug(f"[Lean] Version check failed: {e}")

        self._lean_available = False
        logger.info("[Lean] Not found — will use LLM-simulated verification")
        return False

    async def verify_file(self, lean_file: Path, timeout: int = 120) -> LeanVerificationResult:
        """Verify a Lean 4 file using lake build or lean --run."""
        start = time.monotonic()

        if not await self.check_lean_installation():
            return await self._llm_simulated_verify(lean_file)

        try:
            res = await run_args(
                ["lean", str(lean_file)],
                cwd=self._workspace,
                timeout_s=float(timeout),
                max_stdout_chars=20000,
                max_stderr_chars=20000,
                label="lean.verify_file",
            )
            elapsed = time.monotonic() - start
            if res.timed_out:
                return LeanVerificationResult(
                    success=False,
                    errors=[f"Lean verification timed out after {timeout}s"],
                    execution_time=elapsed,
                )
            output = (res.stdout or "") + (res.stderr or "")

            errors = []
            warnings = []
            sorry_count = 0

            for line in output.splitlines():
                if "error" in line.lower():
                    errors.append(line.strip())
                elif "warning" in line.lower():
                    if "declaration uses 'sorry'" in line:
                        sorry_count += 1
                    warnings.append(line.strip())

            # Also count sorry in source
            content = lean_file.read_text(encoding="utf-8")
            sorry_count = max(sorry_count, content.count("sorry"))

            return LeanVerificationResult(
                success=res.exit_code == 0 and not errors,
                errors=errors,
                warnings=warnings,
                sorry_count=sorry_count,
                execution_time=elapsed,
            )
        except Exception as e:
            return LeanVerificationResult(
                success=False,
                errors=[f"Lean execution error: {e}"],
                execution_time=time.monotonic() - start,
            )

    async def _llm_simulated_verify(self, lean_file: Path) -> LeanVerificationResult:
        """Fallback: use LLM to check Lean code for obvious errors.

        WARNING: This is NOT formal verification. It can catch syntax errors
        and obvious type mismatches, but cannot provide the guarantees of
        actual Lean verification.
        """
        content = lean_file.read_text(encoding="utf-8")
        sorry_count = content.count("sorry")

        # Basic syntactic checks
        errors = []
        if not any(kw in content for kw in ["theorem", "lemma", "def", "example"]):
            errors.append("No theorem/lemma/def declarations found")
        if content.count(":=") + content.count("by") == 0:
            errors.append("No proof body found (missing ':=' or 'by')")

        # Check balanced delimiters
        if content.count("(") != content.count(")"):
            errors.append("Unbalanced parentheses")
        if content.count("{") != content.count("}"):
            errors.append("Unbalanced braces")

        return LeanVerificationResult(
            success=not errors,
            errors=errors,
            warnings=["[SIMULATED] Lean not installed — no formal guarantee"],
            sorry_count=sorry_count,
            execution_time=0.0,
        )

    async def init_project(self, project_dir: Path, name: str = "AutoForgeProof") -> bool:
        """Initialize a Lean 4 project with lake."""
        if not await self.check_lean_installation():
            # Create minimal structure without lake
            project_dir.mkdir(parents=True, exist_ok=True)
            (project_dir / f"{name}.lean").touch()
            return True

        try:
            res = await run_args(
                ["lake", "init", name],
                cwd=project_dir.parent,
                timeout_s=60.0,
                max_stdout_chars=4000,
                max_stderr_chars=4000,
                label="lake.init",
            )
            return res.exit_code == 0 and not res.timed_out
        except Exception as e:
            logger.warning(f"[Lean] Project init failed: {e}")
            project_dir.mkdir(parents=True, exist_ok=True)
            return False


# ══════════════════════════════════════════════════════════════
# Pantograph REPL — Interactive Lean 4 Proof Execution
# ══════════════════════════════════════════════════════════════


class PantographREPL:
    """Interactive REPL-style proof execution for Lean 4.

    Provides machine-to-machine Lean 4 interaction via subprocess:
      - Start a persistent Lean 4 REPL session
      - Send tactics, receive proof state updates
      - Query goals and hypotheses
      - Undo failed tactics
      - Falls back to LLM-simulated tactic application if Lean unavailable

    Inspired by Pantograph (TACAS 2024).
    """

    def __init__(self, lean_env: LeanEnvironment) -> None:
        self._lean_env = lean_env
        self._process: asyncio.subprocess.Process | None = None
        self._current_state: ProofState | None = None
        self._history: list[tuple[str, ProofState]] = []
        self._session_active = False

    async def start_session(self) -> bool:
        """Initialize a Lean 4 REPL session via subprocess.

        Returns True if session started successfully, False if using LLM fallback.
        """
        if not await self._lean_env.check_lean_installation():
            logger.info("[Pantograph] Lean not available — will use LLM simulation")
            return False

        try:
            self._process = await spawn_exec(
                ["lean", "--stdin"],
                cwd=self._lean_env._workspace,
                stdin_pipe=True,
                stdout_pipe=True,
                stderr_pipe=True,
                label="pantograph.repl",
            )
            self._session_active = True
            logger.info("[Pantograph] REPL session started")
            return True
        except Exception as e:
            logger.warning(f"[Pantograph] Failed to start session: {e}")
            self._session_active = False
            return False

    async def send_tactic(self, tactic: str) -> ProofState:
        """Send a tactic to the current proof state.

        Returns the new proof state after tactic application.
        """
        if not self._session_active or not self._process:
            return await self._simulate_tactic(tactic)

        try:
            # Send tactic via stdin
            if self._process.stdin:
                self._process.stdin.write(f"{tactic}\n".encode())
                await self._process.stdin.drain()

            # Read response (simplified — real Pantograph uses structured JSON)
            output = b""
            try:
                while True:
                    chunk = await asyncio.wait_for(
                        self._process.stdout.read(4096),
                        timeout=5.0,
                    )
                    if not chunk:
                        break
                    output += chunk
                    if b"goals" in output or b"error" in output:
                        break
            except asyncio.TimeoutError:
                pass

            response = output.decode(errors="replace")
            new_state = ProofState(
                goals=[line.strip() for line in response.splitlines() if "⊢" in line],
                hypotheses=[],
            )
            self._current_state = new_state
            self._history.append((tactic, new_state))
            return new_state

        except Exception as e:
            logger.warning(f"[Pantograph] Tactic application failed: {e}")
            return await self._simulate_tactic(tactic)

    async def get_goal_state(self) -> ProofState:
        """Query current goals and hypotheses."""
        if self._current_state:
            return self._current_state
        return ProofState(goals=[], hypotheses=[])

    async def undo(self) -> ProofState:
        """Undo the last tactic application."""
        if len(self._history) > 0:
            self._history.pop()
            if self._history:
                _, self._current_state = self._history[-1]
            else:
                self._current_state = ProofState(goals=[], hypotheses=[])
        return self._current_state or ProofState(goals=[], hypotheses=[])

    async def close(self) -> None:
        """Cleanup REPL session."""
        if self._process:
            try:
                self._process.terminate()
                await asyncio.wait_for(self._process.wait(), timeout=5.0)
            except Exception as e:
                logger.debug(f"[Pantograph] Cleanup failed: {e}")
        self._session_active = False

    async def _simulate_tactic(self, tactic: str) -> ProofState:
        """Conservative fallback tactic application.

        Never returns solved goals; this prevents false positives when Lean
        session is unavailable.
        """
        logger.debug(f"[Pantograph] Simulating tactic without formal backend: {tactic}")

        prior_goals = self._current_state.goals if self._current_state else []
        prior_hyps = self._current_state.hypotheses if self._current_state else []
        goals = prior_goals or ["[unknown_goal_state] formal tactic execution unavailable"]

        simulated = ProofState(
            goals=goals,
            hypotheses=prior_hyps,
            context="[simulated] Lean backend unavailable",
            parent_tactic=tactic,
        )
        self._current_state = simulated
        self._history.append((tactic, simulated))
        return simulated


# ══════════════════════════════════════════════════════════════
# Main Engine (Orchestrates Everything)
# ══════════════════════════════════════════════════════════════


class LeanProver:
    """Main Lean 4 theorem proving engine.

    Integrates:
      - LeanEnvironment: Lean 4 toolchain interaction
      - TacticGenerator: multi-source tactic generation
      - MCTSProofSearch: Monte Carlo tree search for proofs
      - RecursiveProofDecomposer: Hilbert-style recursive proving
      - ConjectureEngine: STP self-play for autonomous discovery
      - FoundationBuilder: zero-axiom incremental foundation
      - ArticleFormalizer: formalize math articles into Lean 4
    """

    def __init__(self, workspace: Path | None = None) -> None:
        # Deferred imports to avoid circular dependencies
        from autoforge.engine.provers.proof_search import (
            ConjectureEngine,
            MCTSProofSearch,
            PantographExecutor,
            RecursiveProofDecomposer,
            TacticGenerator,
        )
        from autoforge.engine.provers.proof_library import (
            ArticleFormalizer,
            FoundationBuilder,
            MathlibPremiseSelector,
            PaperReviewPipeline,
            ProofRepairEngine,
        )

        self._workspace = workspace or Path(".")
        self._lean_env = LeanEnvironment(workspace)
        self._tactic_gen = TacticGenerator()
        self._mcts = MCTSProofSearch(
            self._tactic_gen,
            executor=PantographExecutor(self._lean_env),
        )
        self._decomposer = RecursiveProofDecomposer(
            self._tactic_gen,
            self._mcts,
            lean_env=self._lean_env,
        )
        self._conjecture_engine = ConjectureEngine()
        self._foundation = FoundationBuilder()
        self._formalizer = ArticleFormalizer(self._decomposer, self._lean_env)
        # New components
        self._pantograph = PantographREPL(self._lean_env)
        self._premise_selector = MathlibPremiseSelector()
        self._repair_engine = ProofRepairEngine()
        self._paper_reviewer = PaperReviewPipeline(
            self._decomposer,
            self._repair_engine,
            self._premise_selector,
        )

    async def prove_theorem(
        self,
        statement: str,
        llm: Any,
        *,
        informal_statement: str = "",
    ) -> ProofAttempt:
        """Prove a single theorem using the full pipeline."""
        return await self._decomposer.prove(statement, informal_statement, llm)

    async def formalize_article(
        self,
        article_text: str,
        llm: Any,
        *,
        title: str = "Untitled",
    ) -> dict[str, Any]:
        """Formalize a mathematical article into Lean 4."""
        return await self._formalizer.formalize_article(
            article_text, llm, title=title,
        )

    async def build_foundation(
        self,
        llm: Any,
        *,
        max_rounds: int = 10,
        target_tier: DifficultyTier = DifficultyTier.ELEMENTARY,
    ) -> list[FoundationBlock]:
        """Build formal mathematics from scratch (zero-axiom philosophy)."""
        return await self._foundation.bootstrap(
            self._lean_env, llm, self._conjecture_engine,
            self._decomposer,
            max_rounds=max_rounds,
            target_tier=target_tier,
        )

    async def self_play_round(
        self,
        llm: Any,
        *,
        num_conjectures: int = 5,
        domain: str = "general",
    ) -> dict[str, Any]:
        """Run one round of STP self-play: conjecture + prove."""
        from autoforge.engine.provers.proof_library import FoundationBuilder as _FB

        # Get known theorems
        known = (
            self._conjecture_engine.get_proved_theorems()
            or _FB.FOUNDATION_SEEDS
        )

        # Generate conjectures
        conjectures = await self._conjecture_engine.generate_conjectures(
            known, llm, num_conjectures=num_conjectures, domain=domain,
        )

        # Attempt proofs
        results = []
        for conj in conjectures:
            attempt = await self._decomposer.prove(
                conj.lean_statement, conj.informal_statement, llm,
            )
            if attempt.status == ProofStatus.PROVED:
                self._conjecture_engine.record_proof(conj, attempt.lean_proof)
            results.append({
                "conjecture": conj.lean_statement,
                "proved": attempt.status == ProofStatus.PROVED,
                "proof": attempt.lean_proof if attempt.status == ProofStatus.PROVED else "",
            })

        return {
            "round": self._conjecture_engine._generation_round,
            "conjectures": len(conjectures),
            "proved": sum(1 for r in results if r["proved"]),
            "results": results,
            "stats": self._conjecture_engine.get_stats(),
        }

    async def check_lean_available(self) -> bool:
        """Check if Lean 4 is installed."""
        return await self._lean_env.check_lean_installation()

    async def review_paper(
        self,
        article_text: str,
        llm: Any,
        *,
        domain: str = "mathematics",
    ) -> dict[str, Any]:
        """Full paper review pipeline with formal verification.

        Performs:
          1. Structure extraction (claims, theorems, definitions)
          2. Logical consistency checking
          3. Formalization to Lean 4
          4. Proof verification
          5. Novelty assessment
          6. Comprehensive review report with scores + feedback

        Returns detailed review JSON with soundness, formalization, and novelty scores.
        """
        return await self._paper_reviewer.review_paper(
            article_text, llm, domain=domain,
        )

    async def repair_proof(
        self,
        lean_code: str,
        llm: Any,
        *,
        errors: list[str] | None = None,
        max_passes: int = 3,
    ) -> tuple[str, list[str]]:
        """Multi-pass proof repair and sorry elimination.

        Pipeline:
          - Pass 1: Direct LLM-based error fixing
          - Pass 2: Decompose sorries into have-chains
          - Pass 3: Apply automation tactics (simp, omega, aesop, decide)

        Args:
            lean_code: Lean 4 code with errors or sorries
            llm: LLM router
            errors: List of error messages (optional)
            max_passes: Maximum repair iterations

        Returns:
            (repaired_code, remaining_errors)
        """
        if errors is None:
            errors = []
        return await self._repair_engine.repair(
            lean_code, errors, llm, max_passes=max_passes,
        )

    async def search_premises(
        self,
        goal: str,
        llm: Any,
        *,
        domain: str = "",
        top_k: int = 10,
    ) -> list[dict[str, Any]]:
        """Mathlib-aware lemma retrieval for proof goals.

        Uses LLM-based semantic search to find relevant Mathlib lemmas.

        Args:
            goal: The proof goal
            llm: LLM router
            domain: Mathematical domain (algebra, topology, etc.)
            top_k: Number of top lemmas to return

        Returns:
            List of {name, module, type, relevance_score}
        """
        return await self._premise_selector.search_premises(
            goal, llm, domain=domain, top_k=top_k,
        )

    def save_state(self, state_dir: Path) -> None:
        """Persist all prover state."""
        state_dir.mkdir(parents=True, exist_ok=True)
        self._conjecture_engine.save_state(state_dir / "conjectures.json")
        self._foundation.save_state(state_dir / "foundation.json")

        # Export foundation Lean file
        lean_file = state_dir / "foundation.lean"
        lean_file.write_text(
            self._foundation.get_foundation_lean_file(),
            encoding="utf-8",
        )

    def load_state(self, state_dir: Path) -> None:
        """Load prover state."""
        self._conjecture_engine.load_state(state_dir / "conjectures.json")
        self._foundation.load_state(state_dir / "foundation.json")

    def get_stats(self) -> dict[str, Any]:
        """Get comprehensive prover statistics."""
        return {
            "lean_available": self._lean_env._lean_available,
            "lean_version": self._lean_env._lean_version,
            "mcts_stats": self._mcts.get_stats(),
            "conjecture_stats": self._conjecture_engine.get_stats(),
            "foundation_blocks": len(self._foundation._blocks),
            "foundation_tier": self._foundation._current_tier.value,
            "tactic_cache_size": len(self._tactic_gen._success_cache),
            "failure_dict_size": len(self._tactic_gen._failure_dict),
        }
